export const HOME_LOAD_ALL_BEGIN = 'HOME_LOAD_ALL_BEGIN';
export const HOME_LOAD_ALL_SUCCESS = 'HOME_LOAD_ALL_SUCCESS';
export const HOME_LOAD_ALL_FAILURE = 'HOME_LOAD_ALL_FAILURE';
export const HOME_LOAD_ALL_DISMISS_ERROR = 'HOME_LOAD_ALL_DISMISS_ERROR';
