export const CLIENT_CATEGORY_LOAD_MORE_INIT = 'CLIENT_CATEGORY_LOAD_MORE_INIT';
export const CLIENT_CATEGORY_LOAD_MORE_BEGIN = 'CLIENT_CATEGORY_LOAD_MORE_BEGIN';
export const CLIENT_CATEGORY_LOAD_MORE_SUCCESS = 'CLIENT_CATEGORY_LOAD_MORE_SUCCESS';
export const CLIENT_CATEGORY_LOAD_MORE_FAILURE = 'CLIENT_CATEGORY_LOAD_MORE_FAILURE';
export const CLIENT_CATEGORY_LOAD_MORE_DISMISS_ERROR = 'CLIENT_CATEGORY_LOAD_MORE_DISMISS_ERROR';
