export const ALERT_CATEGORY_LOAD_MORE_BEGIN = 'ALERT_CATEGORY_LOAD_MORE_BEGIN';
export const ALERT_CATEGORY_LOAD_MORE_SUCCESS = 'ALERT_CATEGORY_LOAD_MORE_SUCCESS';
export const ALERT_CATEGORY_LOAD_MORE_FAILURE = 'ALERT_CATEGORY_LOAD_MORE_FAILURE';
export const ALERT_CATEGORY_LOAD_MORE_DISMISS_ERROR = 'ALERT_CATEGORY_LOAD_MORE_DISMISS_ERROR';
