export const CONFIG_LOAD_MORE_BEGIN = 'CONFIG_LOAD_MORE_BEGIN';
export const CONFIG_LOAD_MORE_SUCCESS = 'CONFIG_LOAD_MORE_SUCCESS';
export const CONFIG_LOAD_MORE_FAILURE = 'CONFIG_LOAD_MORE_FAILURE';
export const CONFIG_LOAD_MORE_DISMISS_ERROR = 'CONFIG_LOAD_MORE_DISMISS_ERROR';
