export const CAUSE_TYPE_LOAD_MORE_BEGIN = 'CAUSE_TYPE_LOAD_MORE_BEGIN';
export const CAUSE_TYPE_LOAD_MORE_SUCCESS = 'CAUSE_TYPE_LOAD_MORE_SUCCESS';
export const CAUSE_TYPE_LOAD_MORE_FAILURE = 'CAUSE_TYPE_LOAD_MORE_FAILURE';
export const CAUSE_TYPE_LOAD_MORE_DISMISS_ERROR = 'CAUSE_TYPE_LOAD_MORE_DISMISS_ERROR';
export const CAUSE_TYPE_LOAD_ONE_BEGIN = 'CAUSE_TYPE_LOAD_ONE_BEGIN';
export const CAUSE_TYPE_LOAD_ONE_SUCCESS = 'CAUSE_TYPE_LOAD_ONE_SUCCESS';
export const CAUSE_TYPE_LOAD_ONE_FAILURE = 'CAUSE_TYPE_LOAD_ONE_FAILURE';
export const CAUSE_TYPE_LOAD_ONE_DISMISS_ERROR = 'CAUSE_TYPE_LOAD_ONE_DISMISS_ERROR';
