export const FAMILY_LOAD_CHILDREN_INIT = 'FAMILY_LOAD_CHILDREN_INIT';
export const FAMILY_LOAD_CHILDREN_BEGIN = 'FAMILY_LOAD_CHILDREN_BEGIN';
export const FAMILY_LOAD_CHILDREN_SUCCESS = 'FAMILY_LOAD_CHILDREN_SUCCESS';
export const FAMILY_LOAD_CHILDREN_FAILURE = 'FAMILY_LOAD_CHILDREN_FAILURE';
export const FAMILY_LOAD_CHILDREN_DISMISS_ERROR = 'FAMILY_LOAD_CHILDREN_DISMISS_ERROR';
export const FAMILY_TOGGLE = 'FAMILY_TOGGLE';
export const FAMILY_SELECT = 'FAMILY_SELECT';
