export const ALERT_LOAD_MORE_INIT = 'ALERT_LOAD_MORE_INIT';
export const ALERT_LOAD_MORE_BEGIN = 'ALERT_LOAD_MORE_BEGIN';
export const ALERT_LOAD_MORE_SUCCESS = 'ALERT_LOAD_MORE_SUCCESS';
export const ALERT_LOAD_MORE_FAILURE = 'ALERT_LOAD_MORE_FAILURE';
export const ALERT_LOAD_MORE_DISMISS_ERROR = 'ALERT_LOAD_MORE_DISMISS_ERROR';
