export const COUNTRY_LOAD_MORE_INIT = 'COUNTRY_LOAD_MORE_INIT';
export const COUNTRY_LOAD_MORE_BEGIN = 'COUNTRY_LOAD_MORE_BEGIN';
export const COUNTRY_LOAD_MORE_SUCCESS = 'COUNTRY_LOAD_MORE_SUCCESS';
export const COUNTRY_LOAD_MORE_FAILURE = 'COUNTRY_LOAD_MORE_FAILURE';
export const COUNTRY_LOAD_MORE_DISMISS_ERROR = 'COUNTRY_LOAD_MORE_DISMISS_ERROR';
