export const DASHBOARD_LOAD_MORE_BEGIN = 'DASHBOARD_LOAD_MORE_BEGIN';
export const DASHBOARD_LOAD_MORE_SUCCESS = 'DASHBOARD_LOAD_MORE_SUCCESS';
export const DASHBOARD_LOAD_MORE_FAILURE = 'DASHBOARD_LOAD_MORE_FAILURE';
export const DASHBOARD_LOAD_MORE_DISMISS_ERROR = 'DASHBOARD_LOAD_MORE_DISMISS_ERROR';
