export const AGENDA_LOAD_EVENTS_BEGIN = 'AGENDA_LOAD_EVENTS_BEGIN';
export const AGENDA_LOAD_EVENTS_SUCCESS = 'AGENDA_LOAD_EVENTS_SUCCESS';
export const AGENDA_LOAD_EVENTS_FAILURE = 'AGENDA_LOAD_EVENTS_FAILURE';
export const AGENDA_LOAD_EVENTS_DISMISS_ERROR = 'AGENDA_LOAD_EVENTS_DISMISS_ERROR';
