export const INBOX_DOWNLOAD_ONE_BEGIN = 'INBOX_DOWNLOAD_ONE_BEGIN';
export const INBOX_DOWNLOAD_ONE_SUCCESS = 'INBOX_DOWNLOAD_ONE_SUCCESS';
export const INBOX_DOWNLOAD_ONE_FAILURE = 'INBOX_DOWNLOAD_ONE_FAILURE';
export const INBOX_DOWNLOAD_ONE_DISMISS_ERROR = 'INBOX_DOWNLOAD_ONE_DISMISS_ERROR';
export const INBOX_LOAD_MORE_BEGIN = 'INBOX_LOAD_MORE_BEGIN';
export const INBOX_LOAD_MORE_SUCCESS = 'INBOX_LOAD_MORE_SUCCESS';
export const INBOX_LOAD_MORE_FAILURE = 'INBOX_LOAD_MORE_FAILURE';
export const INBOX_LOAD_MORE_DISMISS_ERROR = 'INBOX_LOAD_MORE_DISMISS_ERROR';
