export const JOBQUEUE_LOAD_MORE_INIT = 'JOBQUEUE_LOAD_MORE_INIT';
export const JOBQUEUE_LOAD_MORE_BEGIN = 'JOBQUEUE_LOAD_MORE_BEGIN';
export const JOBQUEUE_LOAD_MORE_SUCCESS = 'JOBQUEUE_LOAD_MORE_SUCCESS';
export const JOBQUEUE_LOAD_MORE_FAILURE = 'JOBQUEUE_LOAD_MORE_FAILURE';
export const JOBQUEUE_LOAD_MORE_DISMISS_ERROR = 'JOBQUEUE_LOAD_MORE_DISMISS_ERROR';
